server:
  port: 8222
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现
      routes: # 配置路由
        - id: service-acl
          predicates: Path=/*/acl/**
          uri: lb://service-acl
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
